# Generated by Django 3.1.7 on 2021-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
